<a href="https://colab.research.google.com/github/poseidon3718/test_0307/blob/main/torch_tutotial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/airobotlab/lecture_1_advanced_cnn/blob/main/1_CNN_%EA%B8%B0%EC%B4%88_%EB%B3%B5%EC%8A%B5.ipynb

Torch Import

In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F

Pooling Example 3x3

In [5]:
input_example1 = torch.tensor([[[0,1.0,2], [3,4,5], [6,7,8]]])
print(input_example)

tensor([[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]])


Max Pooling 각 커널에서 가장 큰 값을 표현

In [6]:
max_pooling_layer1 = nn.MaxPool2d(kernel_size=2, stride=1)
print(max_pooling_layer1)
print(max_pooling_layer1(input_example1))

MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)
tensor([[[4., 5.],
         [7., 8.]]])


Average Pooling 각 커널의 평균 값을 표현

In [7]:
average_pooling_layer = torch.nn.AvgPool2d(kernel_size=2, stride=1)
print(average_pooling_layer1)
print(average_pooling_layer1(input_example1))

AvgPool2d(kernel_size=2, stride=1, padding=0)
tensor([[[2., 3.],
         [5., 6.]]])


Pooling Example 4x4

In [17]:
input_example2 = torch.tensor([[[12,20,30,0.0], [20,12,2,0], [0,70,5,2], [8,2,90,3]]])
print(input_example2)

tensor([[[12., 20., 30.,  0.],
         [20., 12.,  2.,  0.],
         [ 0., 70.,  5.,  2.],
         [ 8.,  2., 90.,  3.]]])


Max Pooling (stride=2) ※ stride: 상하좌우로 움직일 간격 설정

In [20]:
max_pooling_layer2 = nn.MaxPool2d(kernel_size=2, stride=2)
print('\nmax pooling:\n', max_pooling_layer2(input_example2))


max pooling:
 tensor([[[20., 30.],
         [70., 90.]]])


Average Pooling (stride=2)

In [21]:
average_pooling_layer2 = torch.nn.AvgPool2d(kernel_size=2, stride=2)
print('\naverage pooling:\n', average_pooling_layer2(input_example2))


average pooling:
 tensor([[[16.,  8.],
         [20., 25.]]])


Shape Example

In [22]:
inputs = torch.Tensor(1,1,32,32)
inputs.shape

torch.Size([1, 1, 32, 32])

In [23]:
conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, padding=1)
print(conv1)

Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [24]:
conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
print(conv2)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [37]:
pool = nn.MaxPool2d(kernel_size=2)
print(pool)

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)


In [39]:
out = conv1(inputs)
print(out.shape)

torch.Size([1, 32, 32, 32])


In [40]:
out = pool(out)
print(out.shape)

torch.Size([1, 32, 16, 16])


In [41]:
out = conv2(out)
print(out.shape)

torch.Size([1, 64, 16, 16])


In [42]:
out = pool(out)

print(out.shape)

torch.Size([1, 64, 8, 8])


Flatten

In [43]:
out = out.view(out.size(0), -1)
print(out.shape)

torch.Size([1, 4096])


Dense (Fully Connected)

In [44]:
fc = nn.Linear(4096, 10)
out = fc(out)

print(out.shape)
print(out)

torch.Size([1, 10])
tensor([[ 6.0739e+23,  3.5925e+23,  1.0771e+24,  9.3948e+23,  1.0163e+24,
         -6.7802e+23,  1.5825e+24, -7.8404e+23, -1.8807e+23,  2.4470e+23]],
       grad_fn=<AddmmBackward0>)


TensorFlow 예제

In [ ]:
import tensorflow as tf
import
import



input_layer =

flatten_layer =

hidden_layer = Dense(64, activation='relu')(flatten_layer)

output_layer =